### ISSUE TITLE
npm needed as a development dependency?

### ISSUE THREAD

**Issue by njh** [bbc/speculate#23]
Hello,

I am in the process of building/deploying my first service to CentOS 7 using speculate.

I have hit this problem when building/mocking the RPM:

```
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.M5htlJ
+ umask 022
+ cd /builddir/build/BUILD
+ cd radiovis-stomp-server
+ LANG=C
+ export LANG
+ unset DISPLAY
+ npm prune --production
RPM build errors:
/var/tmp/rpm-tmp.M5htlJ: line 32: npm: command not found
error: Bad exit status from /var/tmp/rpm-tmp.M5htlJ (%build)
    Bad exit status from /var/tmp/rpm-tmp.M5htlJ (%build)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.6/site-packages/mockbuild/util.py", line 578, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/radiovis-stomp-server.spec
```

I suspect the problem is that npm isn't installed in the mocking environment, because it isn't listed as a dependency.

But I am surprised that this hasn't been a problem for anyone else?

**Comment by njh** [comment]
I fixed the problem by adding this to ```package.json```:

```json
  "spec": {
    "buildRequires": [
      "npm"
    ]
  }
```

But it feels to me that speculate should add this automatically?

**Comment by DaMouse404** [comment]
Hi @njh, this is usually covered by requiring `nodejs` in `BuildRequires` here:
https://github.com/bbc/speculate/blob/master/templates/spec.mustache#L19

This is due to the packages we use including `npm` in the `nodejs` package since they basically don't work independently. Which distribution of `nodejs` are you using?

**Comment by njh** [comment]
Hi,

The Jenkins slave is running "CentOS release 6.8" - and the ```nodejs``` RPM indeed includes ```/usr/bin/npm```.

I am building for CentOS 7 - so something funny must be going on inside the mock environment. I will try and work out which version of nodejs is being used in there 😟  

How very odd.

nick.

**Comment by njh** [comment]
Just looking on my CentOS 7 Sandbox and it looks like ```npm``` has been split out from the ```nodejs``` RPM:

```
[developer@sandbox7 ~]$ rpm -qf /usr/bin/node
nodejs-6.9.4-2.el7.x86_64
[developer@sandbox7 ~]$ rpm -qf /usr/bin/npm 
npm-3.10.10-1.6.9.4.2.el7.x86_64
```

The ```nodejs``` RPM is quite minimal:
```
[developer@sandbox7 ~]$ rpm -ql nodejs
/usr/bin/node
/usr/lib/dtrace
/usr/lib/dtrace/node.d
/usr/lib/node_modules
/usr/lib/rpm/fileattrs/nodejs_native.attr
/usr/lib/rpm/nodejs_native.req
/usr/share/doc/nodejs-6.9.4
/usr/share/doc/nodejs-6.9.4/AUTHORS
/usr/share/doc/nodejs-6.9.4/CHANGELOG.md
/usr/share/doc/nodejs-6.9.4/COLLABORATOR_GUIDE.md
/usr/share/doc/nodejs-6.9.4/GOVERNANCE.md
/usr/share/doc/nodejs-6.9.4/README.md
/usr/share/doc/nodejs-6.9.4/ROADMAP.md
/usr/share/doc/nodejs-6.9.4/WORKING_GROUPS.md
/usr/share/licenses/nodejs-6.9.4
/usr/share/licenses/nodejs-6.9.4/LICENSE
/usr/share/man/man1/node.1.gz
/usr/share/man/man1/npm-README.1.gz
/usr/share/man/man1/npm-access.1.gz
/usr/share/man/man1/npm-adduser.1.gz
/usr/share/man/man1/npm-bin.1.gz
...
/usr/share/node
/usr/share/systemtap
/usr/share/systemtap/tapset
/usr/share/systemtap/tapset/node.stp
```

(I suspect the npm man pages being in there is a bug)

The RPM came from EPEL:
http://download.fedoraproject.org/pub/epel/7/x86_64/

**Comment by DaMouse404** [comment]
It's probably worth investigating if the nodesource rpm also `Provides: npm` so that we can add both into the RPM spec. Not sure I time to investigate this thoroughly, if it continues to work with the nodesource RPM I'm happy to take it in as a PR 😸

**Comment by njh** [comment]
I need to look into this some more. I am confused as to why it was a problem at all.

This says that the nodejs RPM depends upon the npm RPM. So I don't understand how ```mock``` was unable to find npm:

```
$ rpm -qR nodejs
/bin/sh
ca-certificates
libc.so.6()(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.15)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.3)(64bit)
libc.so.6(GLIBC_2.3.4)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libcrypto.so.10()(64bit)
libcrypto.so.10(OPENSSL_1.0.1_EC)(64bit)
libcrypto.so.10(libcrypto.so.10)(64bit)
libdl.so.2()(64bit)
libdl.so.2(GLIBC_2.2.5)(64bit)
libgcc_s.so.1()(64bit)
libgcc_s.so.1(GCC_3.0)(64bit)
libgcc_s.so.1(GCC_3.4)(64bit)
libicudata.so.50()(64bit)
libicui18n.so.50()(64bit)
libicuuc.so.50()(64bit)
libm.so.6()(64bit)
libm.so.6(GLIBC_2.2.5)(64bit)
libpthread.so.0()(64bit)
libpthread.so.0(GLIBC_2.2.5)(64bit)
libpthread.so.0(GLIBC_2.3.2)(64bit)
libpthread.so.0(GLIBC_2.3.3)(64bit)
librt.so.1()(64bit)
librt.so.1(GLIBC_2.2.5)(64bit)
libssl.so.10()(64bit)
libssl.so.10(libssl.so.10)(64bit)
libstdc++.so.6()(64bit)
libstdc++.so.6(CXXABI_1.3)(64bit)
libstdc++.so.6(GLIBCXX_3.4)(64bit)
libstdc++.so.6(GLIBCXX_3.4.11)(64bit)
libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
libstdc++.so.6(GLIBCXX_3.4.18)(64bit)
libstdc++.so.6(GLIBCXX_3.4.9)(64bit)
libuv >= 1:1.9.1
libuv.so.1()(64bit)
libz.so.1()(64bit)
npm = 1:3.10.10-1.6.9.4.2.el7
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rtld(GNU_HASH)
rpmlib(PayloadIsXz) <= 5.2-1
```

**Comment by njh** [comment]
I can't work out why this didn't work for me - I am unable to re-produce the problem now.
